## $OpenXM: OpenXM_contrib2/windows/cpp/Makefile.vc,v 1.1 2009/03/09 16:00:42 ohara Exp $
## Makefile for Visual Studio 2008

CFLAGS= -nologo -MT -W3 -EHsc -Ox -D NDEBUG -D _MBCS
CPPFLAGS= $(CFLAGS)
LD=link
LDFLAGS=-nologo -subsystem:windows -incremental:no
OBJS= cpp.obj cpp_main.obj StdAfx.obj

all: cpp.exe

cpp.exe: $(OBJS)
    $(LD) $(LDFLAGS) -out:$@ $**

clean:
	-@del *.obj

distclean: clean
	-@del cpp.exe
