## $OpenXM: OpenXM_contrib2/windows/post-msg-asirgui/Makefile.vc,v 1.3 2013/11/27 15:47:18 ohara Exp $
## Makefile for Visual Studio 2010

CFLAGS= -nologo -W3 -Ox -D _CRT_SECURE_NO_WARNINGS -GF
LD=link
#LDFLAGS=-nologo -subsystem:console -incremental:no user32.lib
LDFLAGS=-nologo -subsystem:windows -incremental:no user32.lib

all: cmdasir.exe

clean:
	-@del cmdasir.obj
	-@del cmdasir.exe

distclean: clean

cmdasir.exe: cmdasir.obj
	$(LD) $(LDFLAGS) -out:$@ cmdasir.obj 
