/*	Copyright (c) 1987, 1988 by Software Research Associates, Inc.	*/

#ifndef lint
static char rcsid[]=
"$Header$ (SRA)";
#endif /* lint */

#include <stdio.h>
#include "fep_defs.h"
#include "fep_funcs.h"

/*
 * FunctionNameTable
 */
FunctionTableEnt FunctionNameTable[] = {
	{(FUNC)mark,				"mark",
	 "Mark position"},
	{(FUNC)fep_abort,			"abort",
	 "Abort function"},
	{(FUNC)self_insert,			"self-insert",
	 "Insert the character"},
	{(FUNC)beginning_of_line,		"beginning-of-line",
	 "Jump to beginning of line"},
	{(FUNC)backward_character,		"backward-character",
	 "Backward character"},
	{(FUNC)backward_word,			"backward-word",
	 "Backward word (alphanumeric)"},
	{(FUNC)backward_Word,			"backward-Word",
	 "Backward word (non-space)"},
	{(FUNC)end_of_line,			"end-of-line",
	 "Jump to end of line"},
	{(FUNC)forward_character,		"forward-character",
	 "Forward character"},
	{(FUNC)forward_word,			"forward-word",
	 "Forward word (alphanumeric)"},
	{(FUNC)forward_Word,			"forward-Word",
	 "Forward word (non-space)"}, 
	{(FUNC)forward_to_end_of_word,	"forward-to-end-of-word",
	 "Forward to end of word (alphanumeric)"},
	{(FUNC)forward_to_end_of_Word,	"forward-to-end-of-Word",
	 "Forward to end of word (non-space)"},
	{(FUNC)delete_previous_character,	"delete-previous-character",
	 "Delete previous character"},
	{(FUNC)delete_next_character,		"delete-next-character",
	 "Delete next character"},
	{(FUNC)insert_tab,			"insert-tab",
	 "Insert tab"},
	{(FUNC)new_line,			"new-line",
	 "Insert newline"},
	{(FUNC)insert_and_flush,		"insert-and-flush",
	 "Insert the character and flush buffer"},
	{(FUNC)send_eof,			"send-eof",
	 "Send eof"},
	{(FUNC)kill_to_end_of_line,		"kill-to-end-of-line",
	 "Delete current position to eol"},
	{(FUNC)kill_to_top_of_line,		"kill-to-top-of-line",
	 "Delete tol to current position"},
	{(FUNC)delete_to_kill_buffer,		"delete-to-kill-buffer",
	 "Delete resion to buffer"},
	{(FUNC)yank_from_kill_buffer,		"yank-from-kill-buffer",
	 "Yank from kill buffer"},
	{(FUNC)clear_screen,			"clear-screen",
	 "Clear screen"},
	{(FUNC)next_history,			"next-history",
	 "Get next history"},
	{(FUNC)previous_history,		"previous-history",
	 "Get previous history"},
	{(FUNC)insert_next_history,		"insert-next-history",
	 "Insert next history"},
	{(FUNC)insert_previous_history,	"insert-previous-history",
	 "Insert previous history"},
	{(FUNC)insert_current_history,	"insert-current-history",
	 "Insert current history"},
	{(FUNC)ignore,			"ignore",
	 "Ignore"},
	{(FUNC)delete_line,			"delete-line",
	 "Delete whole line"},
	{(FUNC)literal_next,			"literal-next",
	 "Treat next character as literal"},
	{(FUNC)delete_previous_word,		"delete-previous-word",
	 "Delete previous word (alphanumeric)"},
	{(FUNC)delete_previous_Word,		"delete-previous-Word",
	 "Delete previous word (non-space)"},
	{(FUNC)delete_next_word,		"delete-next-word",
	 "Delete next word (alphanumeric)"},
	{(FUNC)delete_next_Word,		"delete-next-Word",
	 "Delete next word (non-space)"},
	{(FUNC)reprint,			"reprint",
	 "Reprint line"},
	{(FUNC)show_history,			"show-history",
	 "Show history"},
	{(FUNC)show_bindings,			"show-bindings",
	 "Show binding table"},
	{(FUNC)expand_file_name,		"expand-file-name",
	 "Expand file name"},
	{(FUNC)list_file_name,		"list-file-name",
	 "List file name"},
	{(FUNC)terminate,			"terminate",
	 "Terminate fep"},
	{(FUNC)suspend,			"suspend",
	 "Suspend fep"},
	{(FUNC)toggle_through,		"toggle-through",
	 "Change transparency mode"},
	{(FUNC)fix_transparency,		"fix-transparency",
	 "Check tty and change transparency mode"},
	{(FUNC)invoke_shell,			"invoke-shell",
	 "Invoke shell process"},
	{(FUNC)search_reverse,		"search-reverse",
	 "Search backward last !history"},
	{(FUNC)search_forward,		"search-forward",
	 "Search forward last !history"},
	{(FUNC)fep_start_script,		"start-script",
	 "Start script"},
	{(FUNC)fep_end_script,		"end-script",
	 "End script"},
	{(FUNC)fep_repaint,			"repaint",
	 "Repaint screen"},
	{(FUNC)view_buffer,			"view-buffer",
	 "View buffer"},
	{(FUNC)show_help,			"help",
	 "Show help"},

	{(FUNC)vi_c,				"vi-c",
	 "Vi c? commands"},
	{(FUNC)vi_d,				"vi-d",
	 "Vi d? commands"},
	{(FUNC)vi_edit,			"vi-edit",
	 "Vi edit commands"},
	{(FUNC)vi_ins_edit,			"vi-ins-edit",
	 "Vi insert mode"},
	{(FUNC)vi_motion,			"vi-motion",
	 "Vi cursor motion commands"},
	{(FUNC)vi_new_line,			"vi-new-line",
	 "Vi new line"},
	{(FUNC)vi_num,			"vi-num",
	 "Vi prefix number"},

	{NULL,				NULL}
};

/*
 * Table of built-in functions
 */
FunctionTableEnt BuiltinFuncTable[] = {
	{(FUNC)bind_to_key,			"fep-bind",
	 "Change binding table"},
	{(FUNC)alias,				"fep-alias",
	 "Set or show aliases"},
	{(FUNC)unalias,			"fep-unalias",
	 "Delete alias"},
	{(FUNC)set,				"fep-set",
	 "Set or show variables"},
	{(FUNC)unset,				"fep-unset",
	 "Unset variables"},
	{(FUNC)fep_chdir,			"fep-cd",
	 "Change directory"},
	{(FUNC)fep_chdir,			"fep-chdir",
	 "Change directory"},
	{(FUNC)fep_pwd,			"fep-pwd",
	 "Print working directory"},
	{(FUNC)fep_history,			"fep-history",
	 "Show history"},
	{(FUNC)fep_echo,			"fep-echo",
	 "Print arguments"},
	{(FUNC)fep_source,			"fep-source",
	 "Read and execute file"},
	{(FUNC)fep_command,			"fep-command",
	 "Invoke unix command"},
	{(FUNC)fep_command,			"fep-!",
	 "Same as fep_command"},
	{(FUNC)fep_save_history,		"fep-save-history",
	 "Save history to file"},
	{(FUNC)fep_read_history,		"fep-read-history",
	 "Read history from file"},
	{(FUNC)fep_read_from_file,		"fep-read-from-file",
	 "Send file contents to slave command"},
	{(FUNC)fep_read_from_file,		"fep-<",
	 "Same as fep_read_from_file"},
	{(FUNC)fep_read_from_command,		"fep-read-from-command",
	 "Send output of command to slave command"},
	{(FUNC)fep_read_from_command,		"fep-<!",
	 "Same as fep_read_from_command"},
	{(FUNC)fep_start_script,		"fep-start-script",
	 "Start script"},
	{(FUNC)fep_start_script,		"fep-script",
	 "Start script"},
	{(FUNC)fep_end_script,		"fep-end-script",
	 "End script"},
	{(FUNC)fep_if,			"fep-if",
	 "Operation \"if\""},
	{(FUNC)fep_if,			"fep-elseif",
	 "Operation \"endif\""},
	{(FUNC)fep_else,			"fep-else",
	 "Operation \"else\""},
	{(FUNC)fep_endif,			"fep-endif",
	 "Operation \"endif\""},
	{(FUNC)(FUNC)terminate,			"fep-exit",
	 "Terminate fep"},
	{(FUNC)suspend,			"fep-suspend",
	 "Suspend fep"},
	{(FUNC)show_bindings,			"fep-show-bind",
	 "Print bindings"},
	{(FUNC)show_bindings,			"fep-showbind",
	 "Print bindings"},
	{(FUNC)fep_repaint,			"fep-repaint",
	 "Repaint screen"},
#ifdef STAT
	{(FUNC)fep_showstat,			"fep-showstat",
	 "Show statistical information"},
#endif
	{NULL,				NULL}
};
